### ISSUE TITLE
2020-03-16 Task List for Requests this Week

### ISSUE THREAD

**Issue by NeoBeum** [NeoBeum/coinex_slacksetup#6]
NB Needs / Info for
- [x] Ambassador Staff Contact List
- [ ] Request Form Templates
- [ ] Templates in General
- [x] Team Leaders
- [x] Process for Submitting Tasks
- [ ] Key Calendar Dates
- [x] Decision for Partnership costs (Atomic Wallet)

NB's Task
- [ ] Create Ambassador Induction page and path for new Ambassadors and Orientation
- [x] Finalise Atomic Wallet Proposal
- [ ] Discussion with Magnum Wallet
- [ ] Followup Contact with Infinito Wallet

Again, the Business, Marketing and Operations Ambassadors would benefit most from this. Referral Ambassador's would benefit too, if wishing to complete additional tasks, referrals are already tracked through the exchange's system. Tracking number of referrals and or quotas for Referral Ambassadors is a possibility for using GitHub. If there is interest in this, I am able to build those extensions for the Ambassador's Pages.
